### ISSUE TITLE
Message/Embed Mentions

### ISSUE THREAD

**Issue by lupus0802** [HazimAr/Discord-Transcripts#6]
Hello,

I came here from the original repo and as this fork was modified two days ago, I decided to use this.

Problem I encounter with this and the original fork is, that Mentions are not formatted. They are displayed in the format <@`ID`>

Do you plan on fixing this?

Kind Regards

**Comment by HazimAr** [comment]
Yes I will be working on it and should be out in the next few days

**Comment by lupus0802** [comment]
Thank you 😄 

You can close this as I don't have permission somehow.

**Comment by HazimAr** [comment]
Ill keep this open and attach a pr when its finished

**Comment by lupus0802** [comment]
Thank you very much!

—Automatisierte Signatur—
Diese Nachricht läuft über Gmail.
________________________________

**Comment by HazimAr** [comment]
After taking a further look this seems like a task that will take a long time to ensure the use of best practices. I will still try to think of a solution but there are a bunch of things to worry about.

- mentioning users
- mentioning roles
- mentioning text channels
- mentioning voice channels

The library doesn't call any of discords API routes meaning it is gonna be a little more difficult to implement this

**Comment by lupus0802** [comment]
You got this, I believe in you 😄

**Comment by HazimAr** [comment]
We will see 😃

**Comment by ItzDerock** [comment]
[Fixed](https://github.com/ItzDerock/discord-html-transcripts/commit/e24759ebd95f3c9f1a42732118907a892e691c15) in original repo!

**Comment by HazimAr** [comment]
@lupus0802 the code has been added with typescript support [here](https://github.com/HazimAr/Discord-Transcripts/commit/a9e0e4ef3a4190fa9751137378ab8e7afbb841f6)
